const listaDeJogos = [
  {
    id: 1,
    nome: "Grand Theft Auto VI",
    categoria: "Ação",
    imagem: "img/gta-vi.png",
    nota: 4.9,
    descricaoCurta: "O aguardado retorno da franquia GTA em Vice City.",
    descricaoLonga: "Grand Theft Auto VI leva os jogadores de volta a Vice City em uma experiência de mundo aberto gigantesca, com dois protagonistas, missões variadas e um nível de realismo sem precedentes.",
    desenvolvedora: "Rockstar Games",
    lancamento: "19/11/2026",
    plataformas: "PS5, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/QdBZY2fkU-0?autoplay=1"
  },
  {
    id: 2,
    nome: "Red Dead Redemption 2",
    categoria: "Aventura",
    imagem: "img/red-dead-redemption-2.jpg",
    nota: 4.9,
    descricaoCurta: "Uma épica jornada no Velho Oeste americano.",
    descricaoLonga: "Acompanhe Arthur Morgan e a gangue Van der Linde em uma história emocionante sobre lealdade, sobrevivência e mudança durante o fim da era dos fora da lei.",
    desenvolvedora: "Rockstar Games",
    lancamento: "26/10/2018",
    plataformas: "PC, PS4, Xbox One",
    trailer: "https://www.youtube.com/embed/eaW0tYpxyp0?autoplay=1"
  },
  {
    id: 3,
    nome: "The Last of Us Part I",
    categoria: "Ação",
    imagem: "img/the-last-of-us-part-i.jpg",
    nota: 4.8,
    descricaoCurta: "A jornada de Joel e Ellie em um mundo devastado.",
    descricaoLonga: "Remake completo do clássico da Naughty Dog, apresentando gráficos modernizados e uma das histórias mais marcantes dos videogames.",
    desenvolvedora: "Naughty Dog",
    lancamento: "02/09/2022",
    plataformas: "PC, PS5",
    trailer: "https://www.youtube.com/embed/WxjeV10H1F0?autoplay=1"
  },
  {
    id: 4,
    nome: "The Last of Us Part II",
    categoria: "Ação",
    imagem: "img/the-last-of-us-part-ii.png",
    nota: 4.7,
    descricaoCurta: "Uma história intensa de vingança e sobrevivência.",
    descricaoLonga: "Ellie embarca em uma jornada perigosa em busca de vingança, enfrentando dilemas morais e desafios emocionais em um mundo pós-apocalíptico.",
    desenvolvedora: "Naughty Dog",
    lancamento: "19/06/2020",
    plataformas: "PS4, PS5",
    trailer: "https://www.youtube.com/embed/W2Wnvvj33Wo?autoplay=1"
  },
  {
    id: 5,
    nome: "God of War Ragnarök",
    categoria: "Ação",
    imagem: "img/god-of-war-ragnarok.jpg",
    nota: 4.9,
    descricaoCurta: "Kratos e Atreus enfrentam o fim dos tempos nórdicos.",
    descricaoLonga: "Viaje pelos Nove Reinos e enfrente deuses e monstros em uma aventura épica baseada na mitologia nórdica.",
    desenvolvedora: "Santa Monica Studio",
    lancamento: "09/11/2022",
    plataformas: "PS4, PS5",
    trailer: "https://www.youtube.com/embed/hfJ4Km46A-0?autoplay=1"
  },
  {
    id: 6,
    nome: "Uncharted 4: A Thief's End",
    categoria: "Aventura",
    imagem: "img/uncharted-4.jpg",
    nota: 4.8,
    descricaoCurta: "Nathan Drake retorna para sua última grande aventura.",
    descricaoLonga: "Explore ruínas antigas, descubra tesouros lendários e viva uma história cinematográfica repleta de ação e mistério.",
    desenvolvedora: "Naughty Dog",
    lancamento: "10/05/2016",
    plataformas: "PC, PS4, PS5",
    trailer: "https://www.youtube.com/embed/hh5HV4iic1Y?si=2GUzgfykmevhc9b9?autoplay=1"
  },
  {
    id: 7,
    nome: "007 First Light",
    categoria: "Ação",
    imagem: "img/007-first-light.jpg",
    nota: 4.6,
    descricaoCurta: "A origem do agente secreto James Bond.",
    descricaoLonga: "Assuma o papel de um jovem James Bond e descubra como ele conquistou seu famoso código 007 em uma aventura cheia de espionagem.",
    desenvolvedora: "IO Interactive",
    lancamento: "2026",
    plataformas: "PC, PS5, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/J4qY9DYE184?si=JlXEqOo3q4oQVsoS&autoplay=1"
  },
  {
    id: 8,
    nome: "Batman: Arkham Knight",
    categoria: "Ação",
    imagem: "img/batman-arkham-knight.jpg",
    nota: 4.8,
    descricaoCurta: "A batalha final do Cavaleiro das Trevas em Gotham.",
    descricaoLonga: "Enfrente Espantalho, Arkham Knight e diversos vilões clássicos utilizando o Batmóvel e todas as habilidades do Batman.",
    desenvolvedora: "Rocksteady Studios",
    lancamento: "23/06/2015",
    plataformas: "PC, PS4, Xbox One",
    trailer: "https://www.youtube.com/embed/wsf78BS9VE0?si=1n1bhJGG1XNAN_n_&autoplay=1"
  },
  {
    id: 9,
    nome: "Marvel's Spider-Man 2",
    categoria: "Ação",
    imagem: "img/marvels-spider-man-2.jpeg",
    nota: 4.8,
    descricaoCurta: "Peter Parker e Miles Morales enfrentam Venom.",
    descricaoLonga: "Balance pelas ruas de Nova York com dois Homens-Aranha e enfrente ameaças como Kraven e Venom em uma aventura espetacular.",
    desenvolvedora: "Insomniac Games",
    lancamento: "20/10/2023",
    plataformas: "PS5",
    trailer: "https://www.youtube.com/embed/nq1M_Wc4FIc?si=n3V_GHmM-mL6BNAV&autoplay=1"
  },
  {
    id: 10,
    nome: "Elden Ring",
    categoria: "RPG",
    imagem: "img/elden-ring.jpg",
    nota: 4.9,
    descricaoCurta: "Explore as Terras Intermédias em um RPG épico.",
    descricaoLonga: "Criado pela FromSoftware, Elden Ring combina exploração em mundo aberto, combates desafiadores e uma rica mitologia.",
    desenvolvedora: "FromSoftware",
    lancamento: "25/02/2022",
    plataformas: "PC, PS4, PS5, Xbox One, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/E3Huy2cdih0?si=-qKF9Nos2SL9rRCs&autoplay=1"
  },
  {
    id: 11,
    nome: "Need for Speed: Most Wanted",
    categoria: "Corrida",
    imagem: "img/nfs-most-wanted.jpg",
    nota: 4.8,
    descricaoCurta: "Torne-se o piloto mais procurado de Rockport.",
    descricaoLonga: "Um dos jogos de corrida mais icônicos de todos os tempos. Vença rivais, fuja da polícia e domine a Lista Negra para se tornar o corredor mais procurado da cidade.",
    desenvolvedora: "EA Black Box",
    lancamento: "15/11/2005",
    plataformas: "PC, PS2, Xbox, GameCube",
    trailer: "https://www.youtube.com/embed/f7PizLICibk?si=JFq2O_wJcuTlPhYV&autoplay=1"
  },
  {
    id: 12,
    nome: "Forza Horizon 6",
    categoria: "Corrida",
    imagem: "img/forza-horizon-6.jpeg",
    nota: 4.9,
    descricaoCurta: "O maior festival automotivo em mundo aberto.",
    descricaoLonga: "Explore cenários impressionantes, participe de corridas e eventos e monte sua coleção de carros em uma experiência de corrida arcade de última geração.",
    desenvolvedora: "Playground Games",
    lancamento: "2026",
    plataformas: "PC, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/p1wFbZwegpk?si=MA1Dasb273XurOxB&autoplay=1"
  },
  {
    id: 13,
    nome: "Horizon Zero Dawn Remastered",
    categoria: "Aventura",
    imagem: "img/horizon-zero-dawn-remastered.jpg",
    nota: 4.8,
    descricaoCurta: "A jornada de Aloy em gráficos renovados.",
    descricaoLonga: "Explore um mundo dominado por máquinas colossais e descubra os segredos do passado da humanidade nesta versão remasterizada do clássico da Guerrilla Games.",
    desenvolvedora: "Guerrilla Games",
    lancamento: "31/10/2024",
    plataformas: "PC, PS5",
    trailer: "https://www.youtube.com/embed/rgDYyxOKBgg?si=MxpgKoQLilWchw7-&autoplay=1"
  },
  {
    id: 14,
    nome: "Resident Evil 4 Remake",
    categoria: "Terror",
    imagem: "img/resident-evil-4-remake.jpg",
    nota: 4.9,
    descricaoCurta: "Leon enfrenta um pesadelo em uma vila isolada.",
    descricaoLonga: "Remake do clássico de survival horror da Capcom, trazendo gráficos modernos, combate aprimorado e uma atmosfera ainda mais assustadora.",
    desenvolvedora: "Capcom",
    lancamento: "24/03/2023",
    plataformas: "PC, PS4, PS5, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/j5Ic2z3_xp0?si=xllG5EH6WZkjqe3h&autoplay=1"
  },
  {
    id: 15,
    nome: "Little Nightmares",
    categoria: "Terror",
    imagem: "img/little-nightmares.png",
    nota: 4.6,
    descricaoCurta: "Uma aventura sombria pelos medos da infância.",
    descricaoLonga: "Controle Six enquanto tenta escapar de um misterioso navio habitado por criaturas grotescas em um mundo assustador e fascinante.",
    desenvolvedora: "Tarsier Studios",
    lancamento: "28/04/2017",
    plataformas: "PC, PS4, Xbox One, Switch",
    trailer: "https://www.youtube.com/embed/aOadxZBsPiA?autoplay=1"
  },
  {
    id: 16,
    nome: "Resident Evil 7: Biohazard",
    categoria: "Terror",
    imagem: "img/resident-evil-7.jpg",
    nota: 4.8,
    descricaoCurta: "O retorno do terror à franquia Resident Evil.",
    descricaoLonga: "Preso na propriedade da família Baker, Ethan Winters precisa sobreviver a horrores inimagináveis em uma experiência de terror em primeira pessoa.",
    desenvolvedora: "Capcom",
    lancamento: "24/01/2017",
    plataformas: "PC, PS4, PS5, Xbox One, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/RgYqQsbKn6w?si=-8FTjIsKnoPH-pOk&autoplay=1"
  },
  {
    id: 17,
    nome: "Mortal Kombat 1",
    categoria: "Luta",
    imagem: "img/mortal-kombat-1.jpeg",
    nota: 4.7,
    descricaoCurta: "Uma nova era do universo Mortal Kombat criada por Liu Kang.",
    descricaoLonga: "Mortal Kombat 1 reinicia a linha do tempo da franquia com versões inéditas dos personagens clássicos. O jogo traz combates brutais, Fatalities icônicos, sistema de Lutadores de Parceria (Kameo Fighters) e um modo história cinematográfico.",
    desenvolvedora: "NetherRealm Studios",
    lancamento: "19/09/2023",
    plataformas: "PC, PS5, Xbox Series X/S, Nintendo Switch",
    trailer: "https://www.youtube.com/embed/UZ6eFEjFfJ0?si=pewy6h8T_HCDIQvg&autoplay=1"
  },
  {
    id: 18,
    nome: "Death Stranding",
    categoria: "Aventura",
    imagem: "img/death-stranding.jpg",
    nota: 4.7,
    descricaoCurta: "Reconecte uma sociedade fraturada no futuro.",
    descricaoLonga: "Sam Porter Bridges deve cruzar um cenário devastado por ameaças sobrenaturais para salvar a humanidade da extinção iminente.",
    desenvolvedora: "Kojima Productions",
    lancamento: "08/11/2019",
    plataformas: "PC, PS4, PS5",
    trailer: "https://www.youtube.com/embed/tCI396HyhbQ?si=Vvku3KJHtvHRZXyf&autoplay=1"
  },
  {
    id: 19,
    nome: "Assassin's Creed Shadows",
    categoria: "Ação",
    imagem: "img/assassins-creed-shadows.png",
    nota: 4.5,
    descricaoCurta: "Viva a fantasia shinobi e samurai no Japão Feudal.",
    descricaoLonga: "Explore o Japão em um mundo aberto dinâmico através das histórias interligadas da shinobi Naoe e do lendário samurai Yasuke.",
    desenvolvedora: "Ubisoft",
    lancamento: "14/02/2025",
    plataformas: "PC, PS5, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/vovkzbtYBC8?autoplay=1"
  },
  {
    id: 20,
    nome: "Battlefield 6",
    categoria: "Ação",
    imagem: "img/battlefield-6.jpg",
    nota: 4.4,
    descricaoCurta: "A evolução do combate militar em larga escala.",
    descricaoLonga: "Retornando às suas raízes modernas com destruição massiva de cenários, guerra total focada no trabalho em equipe e caos absoluto em multiplayer.",
    desenvolvedora: "DICE / EA",
    lancamento: "2025",
    plataformas: "PC, PS5, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/pgNCgJG0vnY?si=yOs5pHfi_Mdx5vWd&autoplay=1"
  },
  {
    id: 21,
    nome: "Black Myth: Wukong",
    categoria: "RPG",
    imagem: "img/black-myth-wukong.jpg",
    nota: 4.9,
    descricaoCurta: "Uma jornada épica inspirada na mitologia chinesa.",
    descricaoLonga: "Como o Predestinado, aventure-se pelo folclore oriental enfrentando criaturas lendárias com habilidades mágicas e maestria no bastão.",
    desenvolvedora: "Game Science",
    lancamento: "20/08/2024",
    plataformas: "PC, PS5, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/pnSsgRJmsCc?si=Ck83YPoZOhNj87xv&autoplay=1"
  },
  {
    id: 22,
    nome: "Call of Duty: Modern Warfare III",
    categoria: "Ação",
    imagem: "img/cod-mw3.png",
    nota: 4.3,
    descricaoCurta: "A Força-Tarefa 141 enfrenta a ameaça definitiva.",
    descricaoLonga: "Capitão Price e sua equipe lutam contra o criminoso de guerra Vladimir Makarov em uma campanha intensa e multiplayer clássico atualizado.",
    desenvolvedora: "Sledgehammer Games / Activision",
    lancamento: "10/11/2023",
    plataformas: "PC, PS4, PS5, Xbox One, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/i3IsLrPeZG8?si=8joX4-XJe1krgg6a&autoplay=1"
  },
  {
    id: 23,
    nome: "Crimson Desert",
    categoria: "RPG",
    imagem: "img/crimson-desert.jpg",
    nota: 4.7,
    descricaoCurta: "Sobreviva no brutal continente de Pywel.",
    descricaoLonga: "Um RPG de ação de mundo aberto épico que narra a luta de mercenários em terras realistas repletas de combates intensos e narrativa profunda.",
    desenvolvedora: "Pearl Abyss",
    lancamento: "2025",
    plataformas: "PC, PS5, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/YHhwdyWkwTQ?si=ApxCyoxcY2tIQDaz&autoplay=1"
  },
  {
    id: 24,
    nome: "Cyberpunk 2077",
    categoria: "RPG",
    imagem: "img/cyberpunk-2077.jpg",
    nota: 4.7,
    descricaoCurta: "Torne-se um mercenário urbano em Night City.",
    descricaoLonga: "Explore uma megalópole obsessiva por poder e modificações corporais na pele de V, vivenciando reviravoltas futuristas insanas.",
    desenvolvedora: "CD Projekt Red",
    lancamento: "10/12/2020",
    plataformas: "PC, PS4, PS5, Xbox One, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/8X2kIfS6fb8?autoplay=1"
  },
  {
    id: 25,
    nome: "Days Gone",
    categoria: "Ação",
    imagem: "img/days-gone.jpg",
    nota: 4.6,
    descricaoCurta: "Enfrente hordas de Freakers na estrada.",
    descricaoLonga: "No papel do motoqueiro Deacon St. John, explore e sobreviva a um perigoso mundo pós-apocalíptico focado em combate, recursos e manutenção de sua moto.",
    desenvolvedora: "Bend Studio",
    lancamento: "26/04/2019",
    plataformas: "PC, PS4",
    trailer: "https://www.youtube.com/embed/FKtaOY9lMvM?autoplay=1"
  },
  {
    id: 26,
    nome: "God of War (2018)",
    categoria: "Ação",
    imagem: "img/god-of-war-2018.jpg",
    nota: 4.9,
    descricaoCurta: "O recomeço de Kratos no reino nórdico.",
    descricaoLonga: "Vivendo como um homem comum longe da sombra dos deuses, Kratos deve se adaptar a terras desconhecidas e ser um pai para Atreus.",
    desenvolvedora: "Santa Monica Studio",
    lancamento: "20/04/2018",
    plataformas: "PC, PS4",
    trailer: "https://www.youtube.com/embed/K0u_kAWLJOA?si=UpKFemVVu9lVkMF6&autoplay=1"
  },
  {
    id: 27,
    nome: "NBA 2K26",
    categoria: "Esporte",
    imagem: "img/nba-2k26.jpg",
    nota: 4.5,
    descricaoCurta: "A simulação definitiva de basquete da nova temporada.",
    descricaoLonga: "Gerencie sua própria carreira no basquete profissional, monte times lendários no MyTEAM e experimente quadras ultrarrealistas nesta edição anual.",
    desenvolvedora: "Visual Concepts / 2K",
    lancamento: "09/2025",
    plataformas: "PC, PS4, PS5, Xbox One, Xbox Series X/S, Switch",
    trailer: "https://www.youtube.com/embed/Mh57YWNaQC4?si=CdRrCBvBqifWEZHm&autoplay=1"
  },
  {
    id: 28,
    nome: "Star Wars Jedi: Survivor",
    categoria: "Aventura",
    imagem: "img/star-wars-jedi-survivor.jpg",
    nota: 4.7,
    descricaoCurta: "Cal Kestis continua sua luta contra o Império.",
    descricaoLonga: "Cinco anos após os eventos do primeiro jogo, Cal precisa ficar um passo à frente da perseguição constante enquanto carrega o fardo de ser um dos últimos Jedi.",
    desenvolvedora: "Respawn Entertainment",
    lancamento: "28/04/2023",
    plataformas: "PC, PS5, Xbox Series X/S",
    trailer: "https://www.youtube.com/embed/VRaobDJjiec?autoplay=1"
  },
  {
    id: 29,
    nome: "Stray",
    categoria: "Aventura",
    imagem: "img/stray.jpg",
    nota: 4.8,
    descricaoCurta: "Explore uma cidade cibernética pelos olhos de um gato.",
    descricaoLonga: "Um gato de rua ferido e perdido precisa desvendar um mistério antigo para escapar de uma cibercidade esquecida e encontrar o caminho de casa.",
    desenvolvedora: "BlueTwelve Studio",
    lancamento: "19/07/2022",
    plataformas: "PC, PS4, PS5, Xbox One, Xbox Series X/S, Switch",
    trailer: "https://www.youtube.com/embed/kJawWyRUOBM?si=OsK0UMTx3bxDdHwu&autoplay=1"
  }
];

const listaDeNoticias = [
  {
    data: "24 JUN 2026",
    titulo: "GTA 6 terá preço acima do padrão e custará até US$ 100, confirma Rockstar",
    resumo:
      "O aguardado Grand Theft Auto VI chega custando US$ 80 em sua versão padrão, o que pode abrir a porteira para que mais jogos comecem a cobrar esse valor. Confira mais detalhes.",
  },
  {
    data: "20 JUN 2026",
    titulo: "Resident Evil Veronica e o remake de Zero se conectam a Resident Evil Requiem, diz insider",
    resumo:
      "O remake de Resident Evil Veronica terá conexão direta com Resident Evil Requiem",
  },
  {
    data: "12 JUN 2026",
    titulo: "Valve confirma novo console portátil",
    resumo:
      "Após o sucesso do Steam Deck, a Valve apresentou oficialmente seu novo dispositivo portátil com hardware atualizado e maior autonomia de bateria.",
  },
  {
    data: "09 JUN 2026",
    titulo: "PlayStation 5 ultrapassa nova marca de vendas",
    resumo:
      "O PS5 continua dominando o mercado de consoles e alcançou mais uma marca histórica em unidades vendidas mundialmente.",
  },
  {
    data: "06 JUN 2026",
    titulo: "Escassez de memória RAM preocupa fabricantes",
    resumo:
      "A crescente demanda por inteligência artificial e data centers está pressionando a produção de memória RAM e elevando os preços do mercado.",
  },
  {
    data: "03 JUN 2026",
    titulo: "Forza Horizon 6 recebe atualização gratuita",
    resumo:
      "Novos carros, eventos sazonais e melhorias de desempenho chegam ao mais recente jogo de corrida da Playground Games.",
  },
  {
    data: "31 MAI 2026",
    titulo: "Mortal Kombat 1 anuncia novo lutador DLC",
    resumo:
      "A NetherRealm Studios confirmou a chegada de um personagem muito pedido pela comunidade para o elenco do jogo.",
  },
  {
    data: "28 MAI 2026",
    titulo: "Marvel's Spider-Man 2 ganha expansão",
    resumo:
      "A Insomniac Games revelou uma expansão inédita com novas missões, trajes e vilões para Peter Parker e Miles Morales.",
  },
  {
    data: "24 MAI 2026",
    titulo: "God of War Ragnarök alcança marco histórico",
    resumo:
      "O título da Santa Monica Studio ultrapassou mais uma importante marca de vendas e continua entre os jogos mais populares da PlayStation.",
  },
  {
    data: "20 MAI 2026",
    titulo: "Resident Evil 4 Remake supera expectativas",
    resumo:
      "A Capcom divulgou novos números de vendas e confirmou que o remake continua sendo um dos maiores sucessos recentes da empresa.",
  }
];